### ISSUE TITLE
error: unrecognized arguments: chromosome_1

### ISSUE THREAD

**Issue by elcortegano** [pbasting/RATT-with-GFF#3]
I got the following error when running RATTwithGFF:

 
><RATTwithGFF.py> converting chromosome_1.gff to chromosome_1.embl....
usage: EMBLmyGFF3 [-h] [-a] [-c CREATED]
                  [-d {CON,PAT,EST,GSS,HTC,HTG,MGA,WGS,TSA,STS,STD}]
                  [-g ORGANELLE] [-i LOCUS_TAG] [-k KEYWORD [KEYWORD ...]]
                  [-l CLASSIFICATION]
                  [-m {genomic DNA,genomic RNA,mRNA,tRNA,rRNA,other RNA,other DNA,transcribed RNA,viral cRNA,unassigned DNA,unassigned RNA}]
                  [-o OUTPUT] [-p PROJECT_ID] [-q]
                  [-r {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25}]
                  [-s SPECIES] [-t {linear,circular}] [-v]
                  [-x {PHG,ENV,FUN,HUM,INV,MAM,VRT,MUS,PLN,PRO,ROD,SYN,TGN,UNC,VRL}]
                  [-z] [--ah {One of the parameters above}] [--de DE]
                  [--ra RA [RA ...]] [--rc RC] [--rg RG] [--rl RL] [--rt RT]
                  [--rx RX] [--email EMAIL] [--expose_translations]
                  [--force_unknown_features] [--force_uncomplete_features]
                  [--interleave_genes] [--keep_duplicates]
                  [--locus_numbering_start LOCUS_NUMBERING_START]
                  [--no_progress] [--no_wrap_qualifier] [--shame]
                  [--translate]
                  [--use_attribute_value_as_locus_tag USE_ATTRIBUTE_VALUE_AS_LOCUS_TAG]
                  [--uncompressed_log] [--version VERSION] [--strain STRAIN]
                  [--environmental_sample]
                  [--isolation_source ISOLATION_SOURCE] [--isolate ISOLATE]
                  gff_file fasta
EMBLmyGFF3: error: unrecognized arguments: chromosome_1

>fixing line-breaks for: chromosome_1.embl....
Traceback (most recent call last):
  File "./RATTwithGFF.py", line 672, in <module>
    main()
  File "./RATTwithGFF.py", line 48, in main
    gffsToEmbls(contigs)
  File "./RATTwithGFF.py", line 200, in gffsToEmbls
    cleanEmbl(contig)
  File "./RATTwithGFF.py", line 256, in cleanEmbl
    cleanEmblLines = fixBrokenLines(embl)
  File "./RATTwithGFF.py", line 240, in fixBrokenLines
    with open(fileName) as file:
IOError: [Errno 2] No such file or directory: 'contig_embl/chromosome_1_tmp1.embl'

I have traced the error to the `-a` (`--accession`) option of EMBLmyGFF3, which is passed with the value "contig" (eg. it can be "chromosome_1"), but according to EMBLmyGFF3 it should be a boolean.

If this option is removed, EMBLmyGFF3 runs and the script continues. However, I am still not confident that this is the expected behaviour in RATT-with-GFF. What should be the value of the `a` option? is it necessary in the pipeline?

Thank you

**Comment by Ch3mmy** [comment]
I have the name error with you.
and I have test the example of this script，I got the same error.
So I think this script have problem,we need to change the **-a contig** options
